BusinessOrganisationBundle_homepage:
    resource: "@BusinessOrganisationBundle/Resources/config/routing.yml"
    prefix:   /
    
BusinessOrganisationBundle_organisation:
    resource: "@BusinessOrganisationBundle/Resources/config/routing/organisation.yml"
    prefix:   /organisation

business_organisation_cfamily:
    resource: "@BusinessOrganisationBundle/Resources/config/routing/cfamily.yml"
    prefix:   /cfamily
    
business_organisation_criteria:
    resource: "@BusinessOrganisationBundle/Resources/config/routing/criteria.yml"
    prefix:   /criteria

business_organisation_excel:
    resource: "@BusinessOrganisationBundle/Resources/config/routing.yml"
    prefix:   /





# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
