<?php

namespace Business\OrganisationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CbyOrgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CbyOrgRepository extends EntityRepository
{
}
