<?php

namespace Business\OrganisationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CfamilyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CfamilyRepository extends EntityRepository
{
}
